### PR TITLE
Update developer_docs.md

### PR DESCRIPTION
**Pull request by matamadio**
```
make autobuild
```
doesn't seem to work for me, but this does:

```
make html
```

### CODE REVIEW

**Comment by duncandewhurst** [comment]
What was the problem with `make autobuild`? Please could you paste the full output that you get when trying to run the command here so that I can help with troubleshooting?

I set up a fresh development environment according to the instructions in https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#set-up-a-local-development-environment and was able to run `make autobuild` without any issues.

**Comment by matamadio** [comment]
`What was the problem with make autobuild? Please could you paste the full output that you get when trying to run the command here so that I can help with troubleshooting?`

When running `make autobuild` in cmd line it does nothing (no error, no output).
I tried to delete the _build folder, but no change.
While `make html` does create the _build folder.

**Comment by duncandewhurst** [comment]
Hmm, that's odd. What operating system are you using?

**Comment by matamadio** [comment]
I'm on Win 10, using Anaconda.

```
# packages in environment at C:\Users\...\Anaconda3\envs\rdl-standard:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.11.0                   pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7       py311haa95532_0
charset-normalizer        2.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
console_shortcut          0.1.1                         4
docutils                  0.17.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonref                   1.0.1                    pypi_0    pypi
libffi                    3.4.2                hd77b12b_6
livereload                2.6.3                    pypi_0    pypi
markdown-it-py            2.1.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
myst-parser               0.18.1                   pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 22.0                     pypi_0    pypi
pip                       23.0.1          py311haa95532_0
pygments                  2.13.0                   pypi_0    pypi
python                    3.11.3               h966fe2a_0
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
setuptools                66.0.0          py311haa95532_0
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinx-autobuild          2021.3.14                pypi_0    pypi
sphinx-design             0.3.0                    pypi_0    pypi
sphinx-intl               2.0.1                    pypi_0    pypi
sphinx-rtd-theme          1.1.1                    pypi_0    pypi
sphinx-togglebutton       0.3.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-mermaid     0.8.1                    pypi_0    pypi
sphinxcontrib-opendataservices 0.5.0                    pypi_0    pypi
sphinxcontrib-opendataservices-jsonschema 0.5.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tornado                   6.2                      pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.11                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.40.0                   pypi_0    pypi
xz                        5.2.10               h8cc25b3_1
zlib                      1.2.13               h8cc25b3_0
```

**Comment by duncandewhurst** [comment]
Ah, I guess it's something to do with Windows or Anaconda in that case. Please can you run `make autobuild --debug` and copy-paste the output here?

**Comment by matamadio** [comment]
> Please can you run make autobuild --debug and copy-paste the output here?

The command does nothing :\

immagine

**Comment by duncandewhurst** [comment]
Oh dear, how unhelpful! I will try and reproduce the issue on a Windows machine.

`make autobuild` is a really useful feature so I'd prefer to keep that in the docs, but if we can't figure out the issue, we can always add a note to recommend using `make html` in the case of any problems.

**Comment by matamadio** [comment]
Yes please just add the note to use `make html` if the autobuild doesn't work, don't bother replicating the issue.

**Comment by duncandewhurst** [comment]
I've created a [PR](https://github.com/GFDRR/rdl-standard/pull/80) to do that so I'll close this one.

**Pull request closed without merging**
