### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by stufraser1**
**Related issues**

**Description**

**Merge checklist**

- [ ] Update the changelog ([style guide](developer_docs.md#changelog-style-guide))
- [ ] Run `./manage.py` pre-commit

If you added or removed a field:

- [ ] Update the `collapse` option of the jsonschema directives for dataset, resource, hazard, exposure, vulnerability and loss on `reference/schema.md`

### CODE REVIEW

**Comment by stufraser1** [comment]
This was the changelog update related to #130 and I'm sure I shouldn't have created a new PR for this so would be helpful if you could guide me through the correct process on this soon

**Comment by duncandewhurst** [comment]
A PR is necessary to make any changes on the `dev` branch so you followed the right process!

There's a conflict, though, because #130 already added a changelog entry:

> - [#130](https://github.com/GFDRR/rdl-standard/pull/130) - 'hazard_type.csv', add descriptions and update codes from abbreviations to human-readable words.

And this PR adds a different one:

> - [#130](https://github.com/GFDRR/rdl-standard/pull/130) - 'hazard_type.csv' add descriptions and hazard category which aligns with UNDRR Hazard taxonomy.

Which changelog entry do you want to keep?

I suspect this happened because you branched from `dev` before #130 was merged, or you hadn't pulled the latest version of `dev`. We can update https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#propose-changes with a reminder to pull the latest changes before branching if you like?

**Comment by stufraser1** [comment]
> Which changelog entry do you want to keep?

This one: https://github.com/GFDRR/rdl-standard/pull/130 - 'hazard_type.csv' add descriptions and hazard category which aligns with UNDRR Hazard taxonomy.

**Review by odscjen — APPROVED** [review]
I've combined the 2 entries for the same PR

**Pull request merged**
