### PR TITLE
Initial set of RDL codes in CSV format

### PR DESCRIPTION
**Pull request by ConnectedSystems**
As discussed in #11

Initial set of CSV files specifying RDL codes, as currently used in RDL-JKAN.

All aspects, including directory location/structure up for discussion.

### CODE REVIEW

**Review by ldodds — APPROVED** [review]
Looks good to me. I'd originally suggested having these in a `specs/code-lists` folder. As they're part of the specification for the standards, but that could be changed later.

It'd also be useful to have a README in the folder containing the CSV files that gives the name of each code-list and links to the CSV.

But we could reorganise that if these are merged in?

**Review by matamadio — APPROVED** [review]
Looks good, agreeing on Leigh suggestions.
Hazard codes and imt to be later updated according to review in https://github.com/GFDRR/rdl-standard/issues/2

**Comment by ConnectedSystems** [comment]
@ldodds Moved files into 

`specs/code-lists/CSV` to allow same/similar entries in different formats

**Comment by ConnectedSystems** [comment]
Thanks for your input @ldodds @matamadio , I will merge this in now.

**Pull request merged**
