### PR TITLE
docs: Restructure and update landing page content

### LINKED ISSUE #159: [Docs update] Remove GED4all exposure taxonomy page
it’s basically just repeating the information that's on the GED4all webpage and this is creating an extra unnecessary thing to keep up-to-date with the risk of it going out of sync.

### PR DESCRIPTION
**Pull request by duncandewhurst**
**Related issues**

* Related to #43 
* Closes #159
* Related to #155 
* Related to #154 
* Related to #149

**Description**

This PR implements the structure and landing page content proposed in https://github.com/GFDRR/rdl-standard/issues/43#issuecomment-1664775244. Notably, that includes integrating the content from the old taxonomies and GED4ALL pages into the 'other standards' page and linking to it from the relevant sections of the codelist and schema reference pages. It also includes a first draft of content for the new pages in the introduction section: 'What is the RDLS?' and 'How do I implement the RDLS?'. The latter page will need to be updated once the spreadsheet template and conversion and validation tool are available online and once the how-to guide for publishing RDLS metadata is written.

**Merge checklist**

- [x] Update the changelog ([style guide](developer_docs.md#changelog-style-guide))
- [x] Run `./manage.py` pre-commit

If you added or removed a field:

- [ ] Update the `collapse` option of the jsonschema directives for dataset, resource, hazard, exposure, vulnerability and loss on `reference/schema.md`

**Having trouble?**

See [how to resolve check failures](https://github.com/GFDRR/rdl-standard/blob/dev/developer_docs.md#resolve-check-failures).

### CODE REVIEW

**Comment by duncandewhurst** [comment]
These changes are probably easier to review in the built documentation: https://rdl-standard.readthedocs.io/en/43-restructure/

**Comment by odscjen** [comment]
@duncandewhurst I merged the latest dev branch into this PR and it's caused a readthedocs failure. Running this on my own machine the failure appears to be with the `exposure` image in reference/schema.md but I'm not sure what the problem is?

**Review by matamadio — APPROVED** [review]
Flow of information is more intuitive now.

**Comment by duncandewhurst** [comment]
@matamadio are you happy for me to merge this or do you want to wait for @stufraser1 to review?

**Comment by duncandewhurst** [comment]
Agreed to merge in call with @matamadio

**Pull request merged**
